config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  resources :applicants, only: [:create, :update, :show, :new, :edit] do
    collection do
      get :elegibility
      post :check_elegibility, path: "certify"
      post :applySuccess
      get :show
      get :searchApplication
      get :search
      get :new
    end
  end
end

app/models/applicant.rb
class Applicant < ActiveRecord::Base

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :phone_type, presence: true
  validates :workflow_state, presence: true
  validates :region, presence: true

  validates_uniqueness_of :email, case_sensitive: false
  validates_uniqueness_of :phone

  before_validation :init_workflow, on: :create

  #from sqlite3 database

  #select distinct(workflow_state) from applicants
  WORKFLOW_STATE = ["quiz_started", "applied", "quiz_completed", "onboarding_requested", "onboarding_completed", "hired"]
  #select distinct(phone_type) from applicants
  PHONE_TYPE = ["Windows Phone", "Android 2.2/2.3 (over 2 years old)", "iPhone 5/5S", "iPhone 3G/3GS", "iPhone 6/6 Plus", "iPhone 4/4S", "Android 4.0+ (less than 2 years old)", "iPhone 6s/6s Plus", "Blackberry", "Other"]
  #select distinct(region) from applicants
  REGION = ["Chicago", "Boston", "Delhi", "San Francisco Bay Area", "Berlin", "NYC", "Toronto"]

  private

    def init_workflow
      self.workflow_state = WORKFLOW_STATE.first unless workflow_state
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  before_action :set_applicant, only: [:show, :edit, :update]

  #no index, we don't want an admin

  # GET /applicants/1
  # GET /applicants/1.json
  def show
  end

  # GET /applicants/new
  def new
    @applicant = Applicant.new
  end

  #go to elegibility page
  def elegibility
  end

  #applicants said they were elegible
  def check_elegibility
    redirect_to applySuccess_applicants_path
  end

  #go to applySuccess page
  def applySuccess
  end

  # GET /applicants/1/edit
  def edit
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(applicant_params)

    respond_to do |format|
      if @applicant.save
        session[:current_user]= @applicant 

        #redirect to elegibility and background check
        format.html { redirect_to elegibility_applicants_path, notice: 'Applicant was successfully created.' }
        format.json { render :show, status: :created, location: @applicant }
      else
        format.html { render :new }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applicants/1
  # PATCH/PUT /applicants/1.json
  def update
    respond_to do |format|
      if @applicant.update(applicant_params)
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { render :show, status: :ok, location: @applicant }
      else
        format.html { render :edit }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end


  #TODO - add security so that only you can see your application - maybe make them input email and last name?


  def searchApplication
  end

  def search
    @applicant = Applicant.find_by_email(params[:email])
    Rails.logger.debug("My object: #{@applicant.inspect}")
    if @applicant.nil?
      render action: 'searchApplication', notice: 'Could not find your application'
    else
      redirect_to @applicant
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_applicant
      @applicant = Applicant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def applicant_params
      params.require(:applicant).permit(:first_name, :last_name, :region, :phone, :email, :phone_type)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/applicants/_form.html.erb
<div class="container">

  <%= form_with(model: applicant, local: true) do |form| %>
  <% if applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% applicant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">

    <div class="form form-signin">

      <div class="row">

        <div class="panel panel-default">

            <div class="panel-body">

              <div class="form-group">

                    <div class="form-group">
                      <%= form.label :first_name %>
                      <%= form.text_field :first_name, id: :applicant_first_name , class:"form-control", required:"required", placeholder:"First Name"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :last_name %>
                      <%= form.text_field :last_name, id: :applicant_last_name , class:"form-control", required:"required", placeholder:"Last Name"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :region %>
                      <div class="form-select">

                           <%= form.select :region, options_for_select(Applicant::REGION, @applicant.region),{ },class: "form-control",required:"required" %>
                      </div>
                      
                    </div>

                    <div class="form-group">
                      <%= form.label :phone %>
                      <%= form.text_field :phone, id: :applicant_phone , class:"form-control", required:"required", placeholder:"Mobile Number"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :email %>
                      <%= form.text_field :email, id: :applicant_email, class:"form-control", placeholder: "Email", type:"email", required:"required"%>
                    </div>

                    <div class="form-group">
                      <p>
                        Phone type
                      </p>
                      <div class="form-select">
                          <%= form.select :phone_type, options_for_select(Applicant::PHONE_TYPE, @applicant.phone_type),{ },class: "form-control",required:"required" %>

                        </div>
                      </div>

                    <div class="form-group">
                      <%= form.label :source %>
                      <%= form.text_field :source, id: :applicant_source , class:"form-control", placeholder:"Source"%>
                    </div>

                    <div class="form-group">
                      <%= form.label :reason %>
                      <%= form.text_field :reason, id: :applicant_reason , class:"form-control", placeholder:"Reason"%>
                    </div>

                    

              </div>
            </div>
        </div>
          <div class="row text-center">
            <%= form.button content_for(:form_button),class: "btnApply" %>
            
          </div>
      </div>
    </div>
  </div>


<% end %>


</div>

app/views/applicants/applySuccess.html.erb
<div class="container margin-top">

  <h2 class="text-center">
    Thank You for Applying
  </h2>
  <div class="form-group text-center">
    <p>
      We will be in contact with you as soon as possible.
      You can view your application 
      <%= link_to('here', applicant_path(session[:current_user]["id"]), html_options = {class:""}) %>
    </p>
  </div>

</div>

app/views/applicants/edit.html.erb
<%= render 'layouts/navbar'%>

<div class="container margin-top">
	<div class="row text-center">
		<h2>
		  Hello 
		  <%= @applicant.first_name %>
		  <br/>
		  Edit your application details
		</h2>
	</div>
	



	<%= render 'form', applicant: @applicant %>

	<div class="row text-center">
		<%= link_to 'Back to details', @applicant ,class:"" %>

	</div>

	

</div>

app/views/applicants/elegibility.html.erb
<div class="container margin-top">

  <h2 class="text-center">Shopper Elegibility</h2>
    <div class="row">
      <div class="panel panel-default">
        <div class="panel-body">
          <p>
            Shoppers are the face of the company and we take this position seriously. Instacart might perform a background check just to make sure everything is in order.
          </p>
          <p>
            In order to be elegible as an Instacart Shopper you must meet certain requirements. 
          </p>
          <br/>
          <p></p>
          <div class="ul">
            <div class="li">Be 21 or over</div>
            <div class="li">Be able to lift between 30-40 lbs with or without an accommodation</div>
            <div class="li">Be eligible to work in the United States</div>
          </div>
          <br/>
          <p>By selecting Submit you certify that you meet all three requirements and I authorize a background check</p>
        </div>
      </div>
    </div>

    <div class="row text-center">
      <%= form_tag applySuccess_applicants_path do %>
        <div class="form-btn">
          <%= button_tag "Submit",class: "btnApply" %>
        </div>
      <% end %>
    </div>
</div>

app/views/applicants/new.html.erb
<%= render 'layouts/navbar'%>

<div class="container margin-top">
  <h2 class="text-center">
    Hello, apply to be an Instacart Shopper!
  </h2>
  <p class="text-center">We need a few details to start your application</p>
</div>


<%= render 'form', applicant: @applicant %>


<div class="container">
  <div class="row text-center margin-bottom">
    <p>
      <%= link_to 'Already applied?', searchApplication_applicants_path ,class:"" %>
    </p>
  </div>
</div>


<%= link_to 'Back', home_index_path %>

app/views/applicants/searchApplication.html.erb
<%= render 'layouts/navbar'%>

<div class="container margin-top">
  <div class="h2 text-center">Enter your email to see your application details</div>
  <div class="form form-signin">
    <%= form_tag search_applicants_path, :method => 'get' do %>
      <div class="row">
        <%= text_field_tag :email, params[:email], :class => "form-control", :required => "required", :type =>"email" %>
        <br/>
      </div>
      <div class="row text-center">
        <%= submit_tag 'Search', :name => nil, :class => "btnApply" %>
      </div>
    <% end %>
  </div>
</div>

app/views/applicants/show.html.erb
<%= render 'layouts/navbar'%>

<p id="notice"><%= notice %></p>

<div class="container margin-top">
  <div class="text-center">
      <h2>Hello <%= @applicant.first_name %> <br> Here are the details of your application</h2>
  </div>

  <div class="form form-signin">

    <div class="row">

      <div class="panel panel-default">

          <div class="panel-body">

              <p>
                <strong>First name:</strong>
                <%= @applicant.first_name %>
              </p>

              <p>
                <strong>Last name:</strong>
                <%= @applicant.last_name %>
              </p>

              <p>
                <strong>Region:</strong>
                <%= @applicant.region %>
              </p>

              <p>
                <strong>Phone:</strong>
                <%= @applicant.phone %>
              </p>

              <p>
                <strong>Email:</strong>
                <%= @applicant.email %>
              </p>

              <p>
                <strong>Phone type:</strong>
                <%= @applicant.phone_type %>
              </p>

              <p>
                <strong>Source:</strong>
                <%= @applicant.source %>
              </p>

              <p>
                <strong>Reason:</strong>
                <%= @applicant.reason %>
              </p>

          </div>

      </div>

    </div>


  </div>

</div>
<div class="container">
  <div class="row text-center">
      <%= link_to 'Edit', edit_applicant_path(@applicant), :class => "btnApply" %>
  </div>
</div>

app/views/home/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action
-->
<div class="container already-applied">
  <div class="row">
    <div class="col-md-12">
      <%= link_to 'Already applied?', searchApplication_applicants_path ,class:"pull-right" %>
    </div>
  </div>
</div>
<div class="jumbotron cover">
  <div class="container">
    <div class="row main">
      <div class="col-md-6 col-md-offset-3">
        <%= image_tag("instaLogo.png", class: "logo") %>
        <h2 class="text-center">Become an Instacart Shopper and getting paid to shop</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 text-center">
        <%= link_to('Apply Today', new_applicant_path, html_options = {class:"btnApply"}) %>
      </div>
    </div>
  </div>
</div>
<div class="container main-container">
  <div class="row video-row">
    <div class="col-md-12 text-center">
      <h3>How does it work?</h3>
      <h4>Watch this short video to learn more about it</h4>
      <iframe allow="autoplay; encrypted-media" frameborder="0" height="315" src="https://www.youtube.com/embed/Ro5yrd1Rkpc?rel=0" width="560"></iframe>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <h3>Sounds like something for you?</h3>
      <h4>Learn more about our positions</h4>
    </div>
  </div>
  <div class="row panels">
    <div class="col-sm-5 col-md-4 col-md-offset-2 box">
      <div class="panel panel-default">
        <%= image_tag("https://images.unsplash.com/photo-1441123285228-1448e608f3d5?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=02bddc01e37b428821dd036309ae1832&auto=format&fit=crop&w=1500&q=80") %>
        <br/>
        <div class="panel-body">
          <h4 class="text-center">Full-Service Shopper</h4>
          <p class="text-center">Shop and deliver orders</p>
          <ul>
            <li>Independent contractor</li>
            <li>Access to a car required</li>
            <li>Choose hours that work for you</li>
            <li>Shop and deliver orders</li>
          </ul>
        </div>
      </div>
    </div>
    <div class="col-sm-5 col-md-4 box">
      <div class="panel panel-default">
        <%= image_tag("https://images.pexels.com/photos/868110/pexels-photo-868110.jpeg?w=940&h=650&dpr=2&auto=compress&cs=tinysrgb") %>
        <br/>
        <div class="panel-body">
          <h4 class="text-center">In-Store Shopper</h4>
          <p class="text-center">Shop orders within a store</p>
          <ul>
            <li>Part-time employee</li>
            <li>No vehicle required</li>
            <li>Flexible schedule</li>
            <li>Shopping only</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="row margin-bottom">
    <div class="col-md-12 text-center">
      <%= link_to('Apply Today', new_applicant_path, html_options = {class:"btnApply"}) %>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Instacart Home', home_index_path, class: 'navbar-brand' %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopperChallengeMzellhuber</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>